<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<AssemblyName>AnkerGltfExporter</AssemblyName>
		<Configurations>Debug;Release</Configurations>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyTitle>AnkerGltfExporter</AssemblyTitle>
		<AssemblyProduct>AnkerGltfExporter</AssemblyProduct>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Contains('Debug'))">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>TRACE;DEBUG;REVIT2023</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Contains('Release'))">
		<DebugType>none</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE;DEBUG;REVIT2023</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
		<PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2022.1.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.6" />
	</ItemGroup>
	<Import Project="..\Common_glTF_Exporter\Common_glTF_Exporter.projitems" Label="Shared" />
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<DistributionFiles Include="$(OutputPath)AnkerGltfExporter.dll" />
			<DistributionFiles Include="$(OutputPath)System.Drawing.Common.dll" />
		</ItemGroup>
		<MakeDir Directories="$(SolutionDir)Distribution\Revit2023" />
		<Copy SourceFiles="@(DistributionFiles)" DestinationFolder="$(SolutionDir)Distribution\Revit2023" />
		<Message Text="Distribution files copied to: $(SolutionDir)Distribution\Revit2023" Importance="high" />
	</Target>
</Project>